config/routes.rb
WorkTime::Application.routes.draw do
  match 'overtime' => "overtime#index", :as => 'overtime', :via => :get
  match 'by_person' => "overtime#show", :as => 'by_person', :via => :get

  match 'report_cofiguration' => 'work_records#configure_report', :as => 'report_cofiguration', :via => :get
  match 'new_report' => 'work_records#create_report_configuration', :as => 'new_report', :via => :post
  
  resources :work_records
  resources :employees
  resources :reports
  
  resources :work_time_cards
  
  root :to => "work_records#index"

end

app/models/employee.rb
#encoding: UTF-8

class Employee < ActiveRecord::Base
  has_many :work_records, :dependent => :destroy
  belongs_to :department
  
  validates_presence_of :first_name, :last_name
  
  def remaining_vacation_leave
    start_date = Date.parse("#{Date.today.year}-01-01")
  	end_date   = Date.parse("#{Date.today.year}-12-31")
  	due_vacation_leave - (work_records.where("date >= ?", start_date).where("date <= ?", end_date).inject(0) {|sum, wr| sum + (wr.vacation_leave/480)}).to_i
  end
  
  def remaining_care_leave
  	start_date = Date.parse("#{Date.today.year}-01-01")
  	end_date   = Date.parse("#{Date.today.year}-12-31")
  	due_care_leave - (work_records.where("date >= ?", start_date).where("date <= ?", end_date).inject(0) {|sum, wr| sum + (wr.care_leave/480)}).to_i
  end
  
  def full_name
    "#{last_name} #{first_name}"
  end
end

app/controllers/employees_controller.rb
#encoding: UTF-8

class EmployeesController < ApplicationController
  def index
    @employees = Employee.scoped
    @employees = @employees.where(:department_id => params[:department_id]) if params[:department_id]
    @employees = @employees.order("last_name ASC")
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
    @departments = Department.all
  end

  def edit
    @employee = Employee.find(params[:id])
    @departments = Department.all
  end

  def create
    params[:employee][:department] = Department.find( (params[:employee][:department]).to_i )
    @employee = Employee.new(params[:employee])

    if @employee.save
      redirect_to(@employee, :notice => t(:successfully_added_employee))
    else
      @departments = Department.all
      render :action => "new"
    end
  end

  def update
    params[:employee][:department] = Department.find( (params[:employee][:department]).to_i )
    @employee = Employee.find(params[:id])

    if @employee.update_attributes(params[:employee])
      redirect_to(@employee, :notice => t(:successfully_updated_employee))
    else
      @departments = Department.all
      render :action => "edit"
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    redirect_to(employees_url)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <%= render "shared/error_messages", :target => @employee %>
  <table>
    <thead>
      <tr><th colspan="2">Dane osobowe</th></tr>
    </thead>
    <tr>
      <td>Imię</td>
      <td><%= f.text_field :first_name %></td>
    <tr>
    <tr>
      <td>Nazwisko</td>
      <td><%= f.text_field :last_name %></td>
    <tr>
    <tr>
      <td>Wydział</td>
      <td>
        <%= f.select :department, options_for_select(@departments.collect {|d| [ d.name, d.id ] }, @employee.department_id) %>
      </td>
    <tr>
    <tr>
      <td class="no_border_td">&nbsp;</td>
      <td class="no_border_td">&nbsp;</td>
    </tr>

    <thead>
      <tr><th colspan="2">Dane dotyczące urlopów</th></tr>
    </thead>
    <tr>
      <td>Urlop wypoczynkowy należny (w dniach)</td>
      <td><%= f.number_field :due_vacation_leave, :min => 0 %></td>
    </tr>
    <tr>
      <td>Urlop opiekuńczy należny (w dniach)</td>
      <td><%= f.number_field :due_care_leave, :min => 0 %></td>
    </tr>
    <tr>
      <td class="no_border_td">&nbsp;</td>
      <td class="no_border_td">&nbsp;</td>
    </tr>
    <tr>
      <td class="no_border_td">&nbsp;</td>
      <td class="no_border_td" align="right"><%= f.submit 'Zatwierdź' %></td>
    </tr>
  </table>
<% end %>

app/views/employees/edit.html.erb
<% title 'Edycja danych pracownika' %>

<%= render 'form' %>

<%= link_to 'Powrót do listy pracowników', employees_path %>

app/views/employees/index.html.erb
<% title 'Lista pracowników' %>

<div>
  <%= link_to raw('<span>Dodaj nowego pracownika</span>'), new_employee_path, :class => 'button' %>
  <div class="clear"></div>
</div>
<br />
Pokaż pracowników:
<%= link_to 'Wszystkich', employees_url %><%#:department_id => "all" %>
<%= link_to 'Szwalnia', :department_id => "1" %>
<%= link_to 'Rozkrój', :department_id => "2" %>

<table>
  <tr>
    <th>Lp.</th>
    <th>Nazwisko</th>
    <th>Imię</th>
    <th>ID</th>
    <th width="40%">Oddział</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% lp = 0 %>
<% @employees.each do |employee| %>
  <tr>
    <td><%= lp += 1 %></td>
    <td><%= employee.last_name %></td>
    <td><%= employee.first_name %></td>
    <td><%= employee.id %></td>
    <td align="center"><%= employee.department.name %></td>
    <td style="padding: 5px 10px;">
      <%= link_to raw('<img src="/images/show.png" title="Szczegółowe dane pracownika">'), employee_path(employee) %>
    </td>
    <td style="padding: 5px 10px;">
      <%= link_to raw('<img src="/images/edit.png" title="Edycja danych pracownika">'), edit_employee_path(employee) %>
    </td>
    <td style="padding: 5px 10px;">
      <%= link_to raw('<img src="/images/cancel.png" title="Usunięcie pracownika">'), employee, :confirm => 'Czy na pewno usunąć pracownika?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

app/views/employees/new.html.erb
<% title 'Dodawanie nowego pracownika' %>

<%= content_tag :div, "Proszę wypełnić wszystkie pola...", :id => "flash_notice" %>

<%= render 'form' %>

<%= link_to 'Powrót do listy pracowników', employees_path %>

app/views/employees/show.html.erb
<%= title('Szczegółowe dane pracownika') %>

<table class="show_employee">
  <tr>
    <th>ID</th>
    <th>Nazwisko</th>
    <th>Imię</th>
    <th>Oddział</th>
  </tr>
  <tr>
    <td><%= @employee.id %></td>
    <td><%= @employee.last_name %></td>
    <td><%= @employee.first_name %></td>
    <td><%= @employee.department.name %></td>
  </tr>
</table>

<div id="leave_data">
  <table class="show_employee">
    <thead>
      <tr><th colspan="3">Dane urlopów</th></tr>
    </thead>
    <tr>
      <td colspan="3">Urlop wypoczynkowy</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>należny</td>
      <td><%= @employee.due_vacation_leave %> dni</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>pozostały do wykorzystania</td>
      <td><%= @employee.remaining_vacation_leave %> dni</td>
    </tr>
    <tr>
      <td colspan="3">Urlop opiekuńczy</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>należny</td>
      <td><%= @employee.due_care_leave %> dni</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>pozostały do wykorzystania</td>
      <td><%= @employee.remaining_care_leave %> dni</td>
    </tr>
  </table>
</div>

<div class="slick_button">
  <%= slick_button_raw('Edycja danych pracownika', edit_employee_path(@employee)) %>
  <%= slick_button_raw('Powrót do listy wszystkich pracowników', employees_path) %>
  <%= slick_button('Dodaj nowego pracownika...', new_employee_path) %>
</div>