config/routes.rb
WorkTime::Application.routes.draw do
  match 'overtime' => "overtime#index", :as => 'overtime', :via => :get
  match 'by_person' => "overtime#show", :as => 'by_person', :via => :get

  match 'report_cofiguration' => 'work_records#configure_report', :as => 'report_cofiguration', :via => :get
  match 'new_report' => 'work_records#create_report_configuration', :as => 'new_report', :via => :post
  
  resources :work_records
  resources :employees
  resources :reports
  
  resources :work_time_cards
  
  root :to => "work_records#index"

end

app/models/work_record.rb
#encoding: UTF-8

class WorkRecord < ActiveRecord::Base
  belongs_to :employee
  belongs_to :department

  scope :overtime_sum, lambda { |start_date, end_date| select("employee_id").select("SUM(overtime50) as overtime50").select("SUM(overtime100) as overtime100").select("last_name").joins('LEFT JOIN employees ON employees.id = work_records.employee_id').where("date >= ?", start_date).where("date <= ?", end_date).group(:employee_id).order('last_name ASC') }
  scope :by_employee, lambda { |start_date, end_date, employee_id| select("employee_id").select("gr3").select("gr4").select("gr5").select("gr6").select("gr7").select("gr8").select("gr9").select("date").where("date >= ?", start_date).where("date <= ?", end_date).where("employee_id = ?", employee_id) }
  scope :sum_by_employee, lambda { |start_date, end_date, employee_id| select("employee_id").select("SUM(gr3) as gr3").select("SUM(gr4) as gr4").select("SUM(gr5) as gr5").select("SUM(gr6) as gr6").select("SUM(gr7) as gr7").select("SUM(gr8) as gr8").select("SUM(gr9) as gr9").where("date >= ?", start_date).where("date <= ?", end_date).where("employee_id = ?", employee_id).group(:employee_id) }
  
  validates_numericality_of :gr3, :gr4, :gr5, :gr6, :gr7, :gr8, :gr9, :other_work, :cleaning, :layover, :correction, :all_work_time,
    :overtime50, :overtime100, :vacation_leave, :occasional_leave, :sickness, :nn,
    :greater_than_or_equal_to => 0
    
  validate :unique_record, :on => :create

  validate :overtime_entered_if_necessary
  
  def unique_record
    # errors.add_to_base("Dla tego pracownika w danym dniu, dane są już wprowadzone...\nProszę wybrać innego pracownika.") if WorkRecord.where("employee_id = ? AND date = ?", employee_id, date).count > 0
    errors.add(:base, "Dla tego pracownika w danym dniu, dane są już wprowadzone...\nProszę wybrać innego pracownika.") if WorkRecord.where("employee_id = ? AND date = ?", employee_id, date).count > 0
  end

  def overtime_entered_if_necessary
    if (all_work_time > 480 && !(overtime50+overtime100 > 0))
      errors.add(:base, "Coś nie tak z nadgodzinami. Wpisz nadgodziny lub zmniejsz czas pracy do 480 minut.")
    elsif (all_work_time <= 480 && (overtime50+overtime100 > 0))
      errors.add(:base, "Coś nie tak z nadgodzinami. Zwiększ czas pracy ponad 480 minut lub zmiejsz nadgodziny do 0.")
    end
  end
  
  #validates_uniqueness_of :employee_id, :scope => [:date]
  
  def accord_all_groups
    gr3+gr4+gr5+gr6+gr7+gr8+gr9
  end
  
  def productivity
    all_work_time > 0 ? ( accord_all_groups/(all_work_time-other_work-cleaning-layover-correction) ) : 0.0
  end
  
  def calculate_breaks
    all_work_time >= 360 ? BigDecimal.new("15") : BigDecimal.new("0")
  end

  def all_work_time_with_breaks
    all_work_time + breaks
  end

  def overtime
    all_work_time-((breaks/15)*465)
  end
end

app/controllers/work_records_controller.rb
#encoding: UTF-8

class WorkRecordsController < ApplicationController
  def index
    if params[:report] == nil
      params[:report] = Hash.new
      params[:report][:start_date] = "#{Date.today.day}-#{Date.today.month}-#{Date.today.year}"
      params[:department_id] = 1
      
      params[:report][:monthly] = "false"
    end
    
    start_date = Date.parse(params[:report][:start_date])
    end_date = start_date
    
    if params[:report][:monthly] == "true"
      last_day = Date.civil(start_date.year, start_date.month, -1).day
      start_date = Date.civil(start_date.year, start_date.month, 1)
      end_date = Date.civil(start_date.year, start_date.month, last_day)
    end
    department_id = params[:department_id].to_i
    employees = Employee.where(:department_id => department_id)
    
    @work_records = WorkRecord
    .select("work_records.*")
    .select("SUM(gr3) as gr3")
    .select("SUM(gr4) as gr4")
    .select("SUM(gr5) as gr5")
    .select("SUM(gr6) as gr6")
    .select("SUM(gr7) as gr7")
    .select("SUM(gr8) as gr8")
    .select("SUM(gr9) as gr9")
    .select("SUM(other_work) as other_work")
    .select("SUM(cleaning) as cleaning")
    .select("SUM(layover) as layover")
    .select("SUM(correction) as correction")
    .select("SUM(all_work_time) as all_work_time")
    .select("SUM(breaks) as breaks")
    .select("work_records.id as work_record_id")
    .joins('LEFT JOIN employees ON employees.id = work_records.employee_id')
    .where(:department_id => department_id).where("date >= ?", start_date).where("date <= ?", end_date)
    .group(:employee_id).order("last_name ASC")
    
    @grx = WorkRecord.where(:department_id => department_id).where("date >= ?", start_date).where("date <= ?", end_date)
    
    #@gr3_sum = @grx.inject(0.0) {|sum, wr| sum += wr.gr3 }
    #@gr4_sum = @grx.inject(0.0) {|sum, wr| sum += wr.gr4 }
    #@gr5_sum = @grx.inject(0.0) {|sum, wr| sum += wr.gr5 }
    #@gr6_sum = @grx.inject(0.0) {|sum, wr| sum += wr.gr6 }
    #@gr7_sum = @grx.inject(0.0) {|sum, wr| sum += wr.gr7 }
    #@gr8_sum = @grx.inject(0.0) {|sum, wr| sum += wr.gr8 }
    #@gr9_sum = @grx.inject(0.0) {|sum, wr| sum += wr.gr9 }
    
    @gr3_sum = BigDecimal.new('0.0')
    @gr4_sum = BigDecimal.new('0.0')
    @gr5_sum = BigDecimal.new('0.0')
    @gr6_sum = BigDecimal.new('0.0')
    @gr7_sum = BigDecimal.new('0.0')
    @gr8_sum = BigDecimal.new('0.0')
    @gr9_sum = BigDecimal.new('0.0')
    
    @grx.each do |wr|
      @gr3_sum += wr.gr3
      @gr4_sum += wr.gr4
      @gr5_sum += wr.gr5
      @gr6_sum += wr.gr6
      @gr7_sum += wr.gr7
      @gr8_sum += wr.gr8
      @gr9_sum += wr.gr9
    end
    
    ## added code
    
    #all_work_time > 0 ? ( accord_all_groups/(all_work_time-other_work-cleaning-layover-correction) ) : 0.0
    @other_work_sum = @work_records.inject(0.0) {|sum, wr| sum += wr.other_work }
    @cleaning_sum   = @work_records.inject(0.0) {|sum, wr| sum += wr.cleaning }
    @layover_sum    = @work_records.inject(0.0) {|sum, wr| sum += wr.layover }
    @correction_sum = @work_records.inject(0.0) {|sum, wr| sum += wr.correction }
    @breaks_sum     = @work_records.inject(0.0) {|sum, wr| sum += wr.breaks }
    
    ## end of added code
    
    @accord_sum = @work_records.inject(0.0) {|sum, wr| sum += wr.accord_all_groups }
    @all_work_time_sum = @work_records.inject(0.0) {|sum, wr| sum += wr.all_work_time }
    #@productivity_sum = @all_work_time_sum > 0 ? @accord_sum/@all_work_time_sum : 0.0
    @productivity_sum = @all_work_time_sum > 0 ? @accord_sum/(@all_work_time_sum-@other_work_sum-@cleaning_sum-@layover_sum-@correction_sum) : 0.0

    @overtime_sum = @grx.map(&:overtime).sum
    
    store_target_location
    provide_print_version_if_requested
  end

  def show
    @work_record = WorkRecord.find(params[:id])
  end

  def new
    @employees = get_employees_for_report
    
    if params[:employee_id].nil?
      params[:employee_id] = @employees.first.id
    end
    
    @work_record = WorkRecord.new
    @work_record.employee = Employee.find(params[:employee_id])
    @work_record.date = session[:report_date]
    @submit_button_text = "Dalej"
  end

  def edit
    @work_record = WorkRecord.find(params[:id])
    @submit_button_text = "Zatwierdź"
    session[:return_to] = request.referer
  end

  def create
    @work_record = WorkRecord.new(params[:work_record])
    @work_record.department = Department.find(session[:department_id])
    @work_record.breaks = @work_record.calculate_breaks
    @work_record.all_work_time -= @work_record.breaks

    if @work_record.save
      done_count = (WorkRecord.where(:department_id => session[:department_id]).where(:date => session[:report_date])).count
      
      if done_count == Employee.where(:department_id => session[:department_id]).count
        redirect_to(work_records_path, :notice => t(:successfully_added_work_record))
      else
        redirect_to(new_work_record_path, :notice => t(:successfully_added_work_record))
      end
    else
      @submit_button_text = "Dalej"
      @employees = get_employees_for_report
      render :action => "new"
    end
  end

  def update
    @work_record = WorkRecord.find(params[:id])
    @work_record.all_work_time = BigDecimal.new(params[:work_record][:all_work_time])
    @work_record.breaks = @work_record.calculate_breaks
    @work_record.all_work_time -= @work_record.breaks

    params[:work_record].delete :all_work_time
    params[:work_record].delete :breaks

    if @work_record.update_attributes(params[:work_record])
      redirect_to_target_or_default(@work_record, :notice => t(:successfully_updated_work_record))
    else
      @submit_button_text = "Zatwierdź"
      render :action => "edit"
    end
  end

  def destroy
    @work_record = WorkRecord.find(params[:id])
    @work_record.destroy

    redirect_to(work_records_url)
  end
  
  def configure_report
    @departments = Department.all
  end
  
  def create_report_configuration
    #this method should be optimized and cleaned in the future
    session[:department_id] = params[:department_id].to_i
    
    report_date = Date.parse(params[:report_configuration][:date])
    session[:report_date] = report_date
    
    work_records_done = WorkRecord.where(:department_id => session[:department_id]).where(:date => session[:report_date])
    
    if work_records_done.count == Employee.where(:department_id => session[:department_id]).count
      msg = "Na dzień #{report_date}, dla działu #{Department.find(session[:department_id]).name}
      wprowadzono już dane wszystkich pracowników."
      redirect_to(work_records_path, :notice => msg)
    else
      redirect_to new_work_record_path
    end
  end
  
  private
  
  def get_employees_for_report
    work_records_done = WorkRecord.where(:date => session[:report_date]).where(:department_id => session[:department_id])
    employees_done = []
    work_records_done.each {|wr| employees_done.push wr.employee }
    return Employee.where(:department_id => session[:department_id]).all.select {|e| employees_done.include?(e) == false }
  end
end

app/helpers/work_records_helper.rb
module WorkRecordsHelper
  def nice_procent_display(value)
    "#{(value*100).round(2)} %"
  end
end

app/views/work_records/configure_report.html.erb
<% title('Parametry raportu') %>
<% javascript 'jquery-ui-1.8.5.custom.min' %>

<%= content_tag :div, "Wybierz dzień i wydział dla raportu", :id => "flash_notice" %>

<table>
<%= form_tag new_report_path do %>
  <tr>
    <td>Data raportu</td><td><%= text_field 'report_configuration', 'date', :value => nice_date_format(Date.today), :class => 'calendar' %></td>
  </tr>
  <tr>
    <td>Wydział</td><td><%= select_tag :department_id, options_for_select(@departments.collect {|d| [ d.name, d.id ] }) %></td>
  </tr>
  <tr>
    <td>&nbsp;</td><td><%= submit_tag 'Kontynuuj' %></td>
  </tr>
<% end %>
</table>

app/views/work_records/edit.html.erb
<% title('Edycja wpisu') %>

<%= render 'form' %>

<%#= link_to 'Show', @work_record %>

app/views/work_records/index.html.erb
<% title('Czas pracy') %>
<% javascript 'jquery-ui-1.8.5.custom.min', 'jquery.qtip-1.0.0-rc3.min' %>

<p id="information" class="info_box" style="display: none;">
  Znajdujesz się w centrum raportów.<br/>
  Domyślnie wyświetlony jest raport dzienny dla aktualnego dnia, dla działu Szwalnia.
  <br/><br/>
  <b>Aby wyświetlić raport dzienny</b> wybierz konkretny dzień z kalendarza (pole 'Wyświetlić raport z dnia:'), następnie wybierz opcję: 'tylko wybrany dzień' i kliknij przycisk 'Wyświetl'.
  <br/><br/>
  <b>Aby wyświetlić raport z całego miesiąca:</b><br/>
  &nbsp;&nbsp;&nbsp;1. Wybierz w kalendarzu dowolny dzień z miesiąca, dla którego dane chcesz uzyskać.<br/>
  &nbsp;&nbsp;&nbsp;2. Wybierz interesujący dział (Szwalnia lub Rozkrój)<br/>
  &nbsp;&nbsp;&nbsp;3. Zaznacz opcję 'Suma z całego miesiąca'<br/>
  &nbsp;&nbsp;&nbsp;4. Kliknij przycisk 'Wyświetl'
  <br/><br/>
  <b>Aby dodać nowy raport, lub kontynuwać wypełaninie poprzedniego</b> (nie dokończonego raportu), należy kliknąć przycisk 'Utwórz nowy raport lub kontynuuj poprzedni'.
  <br/>
  <a href="#" id="closer" style="margin-left: 67%;">Zamknij tę informację</a>
</p>
<script>
  $(document).ready(function(){
    $('#closer, #opener').click(function(){
      $('#information').slideToggle();
      $('#opener').text() == "Pokaż pomoc" ? $('#opener').text('Ukryj pomoc') : $('#opener').text('Pokaż pomoc');
    });
  });
</script>

<div class="report_params_form">
  <%= link_to raw('<span>Utwórz nowy raport lub kontynuuj poprzedni</span>'), report_cofiguration_path, :class => 'button' %>
  <%#= slick_button('Utwórz nowy raport lub kontynuuj poprzedni', report_cofiguration_path) %>
  <%= slick_button('Drukuj raport', :print => true, :report => {:start_date => params[:report][:start_date], :monthly => params[:report][:monthly] }, :department_id => params[:department_id]) %>
  <div class="clear"></div>
</div>
<div class="report_params_form">
  <%= form_tag '/work_records', :method => 'get', :id => 'report_configuration_form' do -%>
    <table>
      <tr>
        <td>
          <b>Wyświetl raport z dnia:</b>
        </td>
        <td><%= text_field :report, :start_date, :class => 'calendar', :value => params[:report][:start_date] %></td>
      </tr>
      <tr>
        <td><b>Dla działu:</b></td><td><%= select_tag :department_id, options_for_select(Department.all.collect {|d| [d.name, d.id]}, params[:department_id]) %></td>
      </tr>
      <tr>
          <td><b>Typ raportu:</b></td>
          <td>
            <%= radio_button :report, :monthly, "true", :checked => (params[:report][:monthly] == "true" ? 'checked' : 'no') %> Suma z całego miesiąca<br/>
            <%= radio_button :report, :monthly, "false", :checked => (params[:report][:monthly] == "false" ? 'checked' : 'no') %> Tylko wybrany dzień
          </td>
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <div>
            <%= link_to raw('<span>Wyświetl</span>'), "#", :onclick => "document.forms['report_configuration_form'].submit();", :class => 'button' %><a href="#" id="opener" style="margin-bottom: 10px; clear: both;">Pokaż pomoc</a>
            <div class="clear"></div>
          </div>
        </td>
      </tr>
    </table>
    <%#= button_to 'Wyświetl' %>
  <% end -%>
</div>

<br/>

<% 
if params[:report][:monthly] == "true"
  msg = "Raport na miesiąc #{month_name(Date.parse(params[:report][:start_date]).month)} #{Date.parse(params[:report][:start_date]).year}, dla działu: #{Department.find(params[:department_id].to_i).name}"
else
  msg = "Raport z dnia #{params[:report][:start_date]}, dla działu: #{Department.find(params[:department_id].to_i).name}"
end
%>
<%= content_tag :div, msg, :id => "flash_notice", :style => "width: 55%;" %>

<table>
  <thead>
  <tr>
    <th class="small_font" rowspan="2">Lp.</th>
    <th class="small_font" rowspan="2">Pracownik</th>
    <th class="small_font" rowspan="2">Gr3</th>
    <th class="small_font" rowspan="2">Gr4</th>
    <th class="small_font" rowspan="2">Gr5</th>
    <th class="small_font" rowspan="2">Gr6</th>
    <th class="small_font" rowspan="2">Gr7</th>
    <th class="small_font" rowspan="2">Gr8</th>
    <th class="small_font" rowspan="2">Gr9</th>
    <th class="small_font" rowspan="2">Razem akord</th>
    <th class="small_font" rowspan="2">Wydajność</th>
    <th class="small_font" rowspan="2">Inna praca</th>
    <th class="small_font" rowspan="2">Sprzątanie</th>
    <th class="small_font" rowspan="2">Postój / bad. lek.</th>
    <th class="small_font" rowspan="2">Poprawki</th>
    <th class="small_font" colspan="2">Łączny czas<br/>przebywania<br/>w pracy</th>
    <% if params[:report][:monthly] == "true" %>
      <th class="small_font" rowspan="2">Nadgodziny</th>
    <% else -%>
      <th class="dont_print" rowspan="2"></th>
    <% end -%>
  </tr>
  <tr>
    <th class="small_font">Przerwy</th>
    <th class="small_font">Praca</th>
  </tr>
  </thead>
  
  <tbody>

<% lp = 0 %>
<% @work_records.each do |work_record| %>
  <tr class="small_font">
    <td><%= lp += 1 %></td>
    <td style="text-align: left;"><%= "#{work_record.employee.last_name} #{work_record.employee.first_name}"%>
    </td>
    <td><%= work_record.gr3 %></td>
    <td><%= work_record.gr4 %></td>
    <td><%= work_record.gr5 %></td>
    <td><%= work_record.gr6 %></td>
    <td><%= work_record.gr7 %></td>
    <td><%= work_record.gr8 %></td>
    <td><%= work_record.gr9 %></td>
    <td><%= work_record.accord_all_groups %></td>
    <td><%= nice_procent_display(work_record.productivity) %></td>
    <td><%= work_record.other_work %></td>
    <td><%= work_record.cleaning %></td>
    <td><%= work_record.layover %></td>
    <td><%= work_record.correction %></td>
    <td><%= work_record.breaks %></td>
    <td><%= work_record.all_work_time %></td>
    <% if params[:report][:monthly] == "true" %>
      <!-- <td><%#= work_record.all_work_time-((work_record.breaks/15)*465) %></td> -->
      <td><%= work_record.overtime %></td>
    <% else -%>
      <td class="dont_print">
        <%= link_to raw('<img src="/images/edit.png" title="Edytuj wpis">'), edit_work_record_path(work_record.work_record_id) %>
      </td>
    <% end -%>
  </tr>
<% end %>
    <tr class="small_font">
      <td colspan="2"><b>SUMA:</b></td>
      
      <!--td colspan="7"></td-->
      <td><%= @accord_sum > 0 ? (100.0 * @gr3_sum / @accord_sum).to_f.round(1) : 0.0 %> %</td>
      <td><%= @accord_sum > 0 ? (100.0 * @gr4_sum / @accord_sum).to_f.round(1) : 0.0 %> %</td>
      <td><%= @accord_sum > 0 ? (100.0 * @gr5_sum / @accord_sum).to_f.round(1) : 0.0 %> %</td>
      <td><%= @accord_sum > 0 ? (100.0 * @gr6_sum / @accord_sum).to_f.round(1) : 0.0 %> %</td>
      <td><%= @accord_sum > 0 ? (100.0 * @gr7_sum / @accord_sum).to_f.round(1) : 0.0 %> %</td>
      <td><%= @accord_sum > 0 ? (100.0 * @gr8_sum / @accord_sum).to_f.round(1) : 0.0 %> %</td>
      <td><%= @accord_sum > 0 ? (100.0 * @gr9_sum / @accord_sum).to_f.round(1) : 0.0 %> %</td>
      
      <td><%= @accord_sum.round(2) %></td>
      <td><%= nice_procent_display(@productivity_sum) %></td>
      <td><%= @other_work_sum %></td>
      <td><%= @cleaning_sum %></td>
      <td><%= @layover_sum %></td>
      <td><%= @correction_sum %></td>
      <td colspan="1"><%= @breaks_sum %></td>
      <td colspan="1"><%= @all_work_time_sum %></td>
      <td><%= @overtime_sum %></td>
    </tr>
    <tr>
      <th class="small_font">Lp.</th>
      <th class="small_font">Pracownik</th>
      <th class="small_font">Gr3</th>
      <th class="small_font">Gr4</th>
      <th class="small_font">Gr5</th>
      <th class="small_font">Gr6</th>
      <th class="small_font">Gr7</th>
      <th class="small_font">Gr8</th>
      <th class="small_font">Gr9</th>
      <th class="small_font">Razem akord</th>
      <th class="small_font">Wydajność</th>
      <th class="small_font">Inna praca</th>
      <th class="small_font">Sprzątanie</th>
      <th class="small_font">Postój / bad. lek.</th>
      <th class="small_font">Poprawki</th>
      <th class="small_font">Przerwy</th>
      <th class="small_font">Łącznie</th>
      <% if params[:report][:monthly] == "true" %>
        <th class="small_font">Nadgodziny</th>
      <% else -%>
        <th class="dont_print"></th>
      <% end -%>
    </tr>
    <tr><td colspan="18"><sub>Poszczególne procenty w grupach odnoszą się do Razem Akord</sub></td></tr>
    <tr><td colspan="18"><sub><%= msg %></sub></td></tr>
  </tbody>
</table>

app/views/work_records/new.html.erb
<% title('Dodawanie nowego wpisu') %>

<table>
<%= form_tag new_work_record_path, :method => 'get', :id => 'report_configuration_form' do -%>
  <tr>
    <td>Pracownik</td><td><%= select_tag :employee_id, options_for_select(@employees.collect {|e| [ "#{e.last_name} #{e.first_name}", e.id ] }, params[:employee_id]), :onchange => "submit();" %></td>
  </tr>
  <noscript>
  <tr>
    <td>&nbsp;</td><td><%= submit_tag 'OK' %></td>
  </tr>
  </noscript>
<% end %>
</table>

<%= render 'form' %>