config/routes.rb
WorkTime::Application.routes.draw do
  match 'overtime' => "overtime#index", :as => 'overtime', :via => :get
  match 'by_person' => "overtime#show", :as => 'by_person', :via => :get

  match 'report_cofiguration' => 'work_records#configure_report', :as => 'report_cofiguration', :via => :get
  match 'new_report' => 'work_records#create_report_configuration', :as => 'new_report', :via => :post
  
  resources :work_records
  resources :employees
  resources :reports
  
  resources :work_time_cards
  
  root :to => "work_records#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @show_title = show_title
    content_for(:title, page_title.to_s)
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end
  
  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <head>
    <title><%= h(yield(:title) || "Fakturant") %></title>
    <%= stylesheet_link_tag 'application', 'menu', 'button', 'jquery-ui-1.8.5.custom', :media => "all" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container" class="transparent_class">
      <div id="menu_bar">
        <div id="nav">
          <ul>
            <li class="<%= controller.controller_path == 'employees' ? 'selected' : '' %>">
              <%= link_to 'Pracownicy', employees_path %>
            </li>
            <li class="<%= controller.controller_path == 'work_records' ? 'selected' : '' %>">
              <%= link_to 'Czas Pracy', work_records_path %>
            </li>
            <li class="<%= controller.controller_path == 'work_time_cards' ? 'selected' : '' %>">
              <%= link_to 'Miesięczna ewidencja czasu pracy', work_time_cards_path %>
            </li>
            <li class="<%= request.path == '/overtime' ? 'selected' : '' %>">
              <%= link_to 'Suma nadgodzin', overtime_path %>
            </li>
            <li class="<%= request.path == '/by_person' ? 'selected' : '' %>">
              <%= link_to 'Raport godzin pracownika', by_person_path %>
            </li>
            <li class="<%= request.path.include?('/reports') ? 'selected' : '' %>">
              <%= link_to 'Roczna ewidencja czasu pracy', report_path(1) %>
            </li>
          </ul>
        </div>
      </div>
      
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
      
      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= h(yield(:title) || "Fakturant") %></title>
    <%= stylesheet_link_tag 'print', 'menu', 'button', 'jquery-ui-1.8.5.custom', :media => "all" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <!--body onload="window.print();"-->
  <body>
    <div id="container" class="transparent_class">
      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>
      
      <%= yield %>
    </div>
  </body>
</html>